//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_APP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class persons_gadgets
    {
        public int Id { get; set; }
        public int Person_id { get; set; }
        public int Gadget_id { get; set; }
    
        public virtual gadgets gadgets { get; set; }
        public virtual persons persons { get; set; }
    }
}
